[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log
priority=1

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
priority=2

[program:queue-worker]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90 --max-time=3600
directory=/var/www/html
autostart=true
autorestart=true
numprocs=1
stderr_logfile=/var/log/queue-worker.err.log
stdout_logfile=/var/log/queue-worker.out.log
priority=3
stopwaitsecs=60
